[versions]
com-gradleup-nmcp = "0.0.9"
jackson = "2.18.3"
javax-xml-stream = "1.0-2"
junit5 = "5.14.0"
junit5-platform = "1.14.0"
kermit = "2.0.8"
ktfmt-gradle = "0.22.0"
ktor = "3.3.1"
org-jetbrains-dokka = "1.9.20"
org-jetbrains-kotlin-jdk8 = "1.10.1"
org-jetbrains-kotlin-jvm = "2.1.10"
serialization = "1.8.0"
slf4j = "2.0.17"
truth = "1.4.5"

[libraries]
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
javax-xml-stream = { module = "javax.xml.stream:stax-api", version.ref = "javax-xml-stream" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit5-platform" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlin-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "org-jetbrains-kotlin-jdk8" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "serialization" }
ktor-client = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
com-gradleup-nmcp = { id = "com.gradleup.nmcp", version.ref = "com-gradleup-nmcp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "org-jetbrains-kotlin-jvm" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-gradle" }
org-jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "org-jetbrains-dokka" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
